### Association Rules

In [2]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mlxtend in c:\users\croma campus\appdata\roaming\python\python313\site-packages (0.24.0)
Requirement already satisfied: scipy>=1.16.3 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from mlxtend) (1.17.0)
Collecting numpy>=2.3.5 (from mlxtend)
  Downloading numpy-2.5.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: pandas>=2.3.3 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading numpy-2.5.2-cp313-cp313-win_amd64.whl (12.5 MB)
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.5 MB 11.7 MB/s eta 0:00:01
   ------------ --------------------------- 3.9/12.5 MB 11.7 MB/s eta 0:00:01
   -------------------- ------------------- 6.3/12.5 MB 11.7 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.5 MB 11.6 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.5 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 10.7 MB/s  0:00:01
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.6
    Uninstalling numpy-2.2.6:
      Successfully uninstalled numpy-2.2.6
Successfully installed numpy-2.5.2

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Croma Campus\AppData\Roaming\Python\Python313\site-packages\~.mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Croma Campus\AppData\Roaming\Python\Python313\site-packages\~.mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.63.1 requires numpy<2.4,>=1.22, but you have numpy 2.5.2 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.5.2 which is incompatible.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
!python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\users\croma campus\appdata\roaming\python\python313\site-packages (25.3)
Collecting pip
  Downloading pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.2.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------- ----------- 1.3/1.8 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 10.4 MB/s  0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfully uninstalled pip-25.3
Successfully installed pip-26.2.1

In [4]:
from mlxtend.frequent_patterns import apriori , association_rules

In [5]:
import pandas as pd

In [6]:
dataset = [
    ["Milk",'Bread'],
    ['Milk','Butter','Jam'],
    ['Milk','Bread','Butter'],
    ['Bread','Butter','Jam','Eggs'],
    ['Milk','Butter','Jam'],
    ['Milk','Eggs','Jam','Butter']
]

In [9]:
from mlxtend.preprocessing import TransactionEncoder

In [10]:
te = TransactionEncoder()

In [11]:
X = te.fit_transform(dataset)

In [12]:
X

array([[ True, False, False, False,  True],
       [False,  True, False,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True, False],
       [False,  True, False,  True,  True],
       [False,  True,  True,  True,  True]])

In [14]:
te.columns_

['Bread', 'Butter', 'Eggs', 'Jam', 'Milk']

In [15]:
df = pd.DataFrame(
    X , columns=te.columns_
)

In [17]:
df

   Bread  Butter   Eggs    Jam   Milk
0   True   False  False  False   True
1  False    True  False   True   True
2   True    True  False  False   True
3   True    True   True   True  False
4  False    True  False   True   True
5  False    True   True   True   True

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Bread   6 non-null      bool
 1   Butter  6 non-null      bool
 2   Eggs    6 non-null      bool
 3   Jam     6 non-null      bool
 4   Milk    6 non-null      bool
dtypes: bool(5)
memory usage: 162.0 bytes

In [22]:
frequent_itemsets = apriori( df , min_support=0.3 , use_colnames=True )

In [23]:
frequent_itemsets

     support             itemsets
0   0.500000              (Bread)
1   0.833333             (Butter)
2   0.333333               (Eggs)
3   0.666667                (Jam)
4   0.833333               (Milk)
5   0.333333      (Bread, Butter)
6   0.333333        (Milk, Bread)
7   0.333333       (Butter, Eggs)
8   0.666667        (Jam, Butter)
9   0.666667       (Milk, Butter)
10  0.333333          (Jam, Eggs)
11  0.500000          (Jam, Milk)
12  0.333333  (Jam, Butter, Eggs)
13  0.500000  (Jam, Butter, Milk)

In [25]:
frequent_itemsets.sort_values( by='support' , ascending=False )

     support             itemsets
1   0.833333             (Butter)
4   0.833333               (Milk)
3   0.666667                (Jam)
9   0.666667       (Milk, Butter)
8   0.666667        (Jam, Butter)
0   0.500000              (Bread)
13  0.500000  (Jam, Butter, Milk)
11  0.500000          (Jam, Milk)
5   0.333333      (Bread, Butter)
2   0.333333               (Eggs)
6   0.333333        (Milk, Bread)
7   0.333333       (Butter, Eggs)
10  0.333333          (Jam, Eggs)
12  0.333333  (Jam, Butter, Eggs)

In [27]:
rules = association_rules( frequent_itemsets , metric='confidence' )

In [28]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Eggs),(Butter),0.333333,0.833333,0.333333,1.0,1.2,1.0,0.055556,inf,0.250000,0.4,1.0,0.70
1,(Jam),(Butter),0.666667,0.833333,0.666667,1.0,1.2,1.0,0.111111,inf,0.500000,0.8,1.0,0.90
2,(Eggs),(Jam),0.333333,0.666667,0.333333,1.0,1.5,1.0,0.111111,inf,0.500000,0.5,1.0,0.75
3,"(Jam, Eggs)",(Butter),0.333333,0.833333,0.333333,1.0,1.2,1.0,0.055556,inf,0.250000,0.4,1.0,0.70
4,"(Butter, Eggs)",(Jam),0.333333,0.666667,0.333333,1.0,1.5,1.0,0.111111,inf,0.500000,0.5,1.0,0.75
5,(Eggs),"(Jam, Butter)",0.333333,0.666667,0.333333,1.0,1.5,1.0,0.111111,inf,0.500000,0.5,1.0,0.75
6,"(Jam, Milk)",(Butter),0.500000,0.833333,0.500000,1.0,1.2,1.0,0.083333,inf,0.333333,0.6,1.0,0.80

In [29]:
rules[['antecedents','consequents','support','confidence','lift']]

      antecedents    consequents   support  confidence  lift
0          (Eggs)       (Butter)  0.333333         1.0   1.2
1           (Jam)       (Butter)  0.666667         1.0   1.2
2          (Eggs)          (Jam)  0.333333         1.0   1.5
3     (Jam, Eggs)       (Butter)  0.333333         1.0   1.2
4  (Butter, Eggs)          (Jam)  0.333333         1.0   1.5
5          (Eggs)  (Jam, Butter)  0.333333         1.0   1.5
6     (Jam, Milk)       (Butter)  0.500000         1.0   1.2