In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("../dataset/iris.csv")

In [13]:
df.shape

(150, 5)

In [14]:
df.head(2)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [15]:
species = list(df['species'].unique())
species

['setosa', 'versicolor', 'virginica']

In [16]:
df['species'] = df['species'].map( lambda val : list(df['species'].unique()).index(val) )

In [17]:
# Divide Data into X and y
X = df.drop(columns=['species'])
y = df['species']

In [18]:
y.head(2)

0    0
1    0
Name: species, dtype: int64

In [21]:
X.head(2)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [22]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler = MinMaxScaler(feature_range=(0,1))

In [23]:
X = scaler.fit_transform(X)

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [31]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [25]:
models = {
    'Logistic Regression':LogisticRegression(),
    'DTC':DecisionTreeClassifier(),
    'RFC':RandomForestClassifier()
}

In [40]:
file = open("../model_report.txt",'w')
for name , model in models.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    print(name ," : ", accuracy_score(y_test,y_pred)*100)
    print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
    print("Classification Report:\n",classification_report(y_test,y_pred))
    file.write(f"\n\n\t\t{name}\n\n")
    file.write("\nAccuracy Score : "+str(accuracy_score(y_test,y_pred)*100) )
    file.write("\nConfusion Matrix\n"+str(confusion_matrix(y_test,y_pred)))
    file.write("\nclassification_report\n"+str(classification_report(y_test,y_pred)))
file.close()

Logistic Regression  :  96.66666666666667
Confusion Matrix:
 [[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

DTC  :  100.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

RFC  :  100.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [ ]:
# Select RFC